vich_uploader:
    db_driver: orm

   # mappings:
    #    product_image:
      #     uri_prefix: '%app.path.products_images%'
      #     upload_destination: '%kernel.project_dir%/public/%app.path.products_images%'
        #   namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        #   inject_on_load: false
        #   delete_on_update: true
          # delete_on_remove: true
